CREATE TABLE [dbo].[Purchase]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TransactionNo] VARCHAR(MAX) NOT NULL, 
	[PartyId] INT NOT NULL,
	[TransactionDateTime] DATETIME NOT NULL,
	[FinancialYearId] INT NOT NULL,
	[ItemsTotalAmount] MONEY NOT NULL DEFAULT 0,
	[CashDiscountPercent] DECIMAL(5, 2) NULL DEFAULT 0,
	[CashDiscountAmount] MONEY NULL DEFAULT 0,
	[OtherChargePercent] DECIMAL(5, 2) NULL DEFAULT 0,
	[OtherChargesAmount] MONEY NULL DEFAULT 0,
	[RoundOffAmount] MONEY NOT NULL DEFAULT 0,
	[TotalAmount] MONEY NOT NULL DEFAULT 0,
	[Remarks] VARCHAR(MAX) NULL,
	[UserId] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'India Standard Time')),
	[CreatedFromPlatform] VARCHAR(MAX) NOT NULL,
	[Status] BIT NOT NULL DEFAULT 1,
	[LastModifiedBy] INT NULL,
	[LastModifiedAt] DATETIME NULL, 
	[LastModifiedFromPlatform] VARCHAR(MAX) NULL,
    CONSTRAINT [FK_Purchase_ToLedger] FOREIGN KEY ([PartyId]) REFERENCES [Ledger]([Id]), 
    CONSTRAINT [FK_Purchase_ToFinancialYear] FOREIGN KEY ([FinancialYearId]) REFERENCES [dbo].[FinancialYear]([Id]),
    CONSTRAINT [FK_Purchase_ToUser] FOREIGN KEY ([UserId]) REFERENCES [User]([Id]),
	CONSTRAINT [FK_Purchase_LastModifiedBy_ToUser] FOREIGN KEY ([LastModifiedBy]) REFERENCES [User]([Id])
)