CREATE TABLE [dbo].[Document]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TransactionNo] VARCHAR(500) NOT NULL UNIQUE,
    [TransactionDateTime] DATETIME NOT NULL,
    [FinancialYearId] INT NOT NULL,
	[DocumentTypeId] INT NOT NULL,
    [VehicleId] INT NOT NULL,
    [CurrentHour] MONEY NULL, 
    [CurrentKM] MONEY NULL,
    [Rate] MONEY NOT NULL,
    [RenewalDate] DATETIME NOT NULL,
    [Remarks] VARCHAR(MAX) NULL,
    [DocumentUrl] VARCHAR(MAX) NULL,
	[CreatedBy] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'India Standard Time')),
	[CreatedFromPlatform] VARCHAR(MAX) NOT NULL,
	[Status] BIT NOT NULL DEFAULT 1,
	[LastModifiedBy] INT NULL,
	[LastModifiedAt] DATETIME NULL, 
	[LastModifiedFromPlatform] VARCHAR(MAX) NULL, 
    CONSTRAINT [FK_Document_ToFinancialYear] FOREIGN KEY ([FinancialYearId]) REFERENCES [FinancialYear](Id),
    CONSTRAINT [FK_Document_ToDocumentType] FOREIGN KEY ([DocumentTypeId]) REFERENCES [DocumentType](Id), 
    CONSTRAINT [FK_Document_ToVehicle] FOREIGN KEY ([VehicleId]) REFERENCES [Vehicle](Id),
    CONSTRAINT [FK_Document_ToUser] FOREIGN KEY ([CreatedBy]) REFERENCES [User]([Id]),
	CONSTRAINT [FK_Document_LastModifiedBy_ToUser] FOREIGN KEY ([LastModifiedBy]) REFERENCES [User]([Id])
)
