CREATE TABLE [dbo].[ItemCategory]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(500) NOT NULL UNIQUE,
	[Code] VARCHAR(50) NOT NULL UNIQUE,
	[Remarks] VARCHAR(MAX) NULL,
	[Status] BIT NOT NULL DEFAULT 1
)
