CREATE TABLE [dbo].[Tax]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(500) NOT NULL UNIQUE,
    [Code] VARCHAR(50) NOT NULL UNIQUE, 
    [CGST] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [SGST] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [IGST] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [Inclusive] BIT NOT NULL DEFAULT 0, 
    [Extra] BIT NOT NULL DEFAULT 0,
    [Remarks] VARCHAR(MAX) NULL,
    [Status] BIT NOT NULL DEFAULT 1
)