<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <UserSecretsId>706def87-8af8-4c7f-a70d-a8423747bd21</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Exporting\Accounts\FinancialAccounting\" />
    <Folder Include="Exporting\Utils\" />
    <Folder Include="Models\Accounts\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.2" />
    <PackageReference Include="MimeKit" Version="4.14.0" />
    <PackageReference Include="NumericWordsConversion" Version="2.1.1" />
    <PackageReference Include="Syncfusion.Pdf.Net.Core" Version="32.1.24" />
    <PackageReference Include="Syncfusion.XlsIO.Net.Core" Version="32.1.24" />
  </ItemGroup>

</Project>
