CREATE TABLE [dbo].[PurchaseReturn]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TransactionNo] VARCHAR(MAX) NOT NULL, 
	[CompanyId] INT NOT NULL,
	[PartyId] INT NOT NULL,
	[TransactionDateTime] DATETIME NOT NULL,
	[FinancialYearId] INT NOT NULL,
	[TotalItems] INT NOT NULL DEFAULT 0,
	[TotalQuantity] MONEY NOT NULL DEFAULT 0,
	[BaseTotal] MONEY NOT NULL DEFAULT 0,
	[ItemDiscountAmount] MONEY NOT NULL DEFAULT 0,
	[TotalAfterItemDiscount] MONEY NOT NULL DEFAULT 0,
	[TotalInclusiveTaxAmount] MONEY NOT NULL DEFAULT 0,
	[TotalExtraTaxAmount] MONEY NOT NULL DEFAULT 0,
	[TotalAfterTax] MONEY NOT NULL DEFAULT 0,
	[OtherChargesPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0,
	[OtherChargesAmount] MONEY NOT NULL DEFAULT 0,
	[CashDiscountPercent] DECIMAL(5, 2) NOT NULL DEFAULT 0,
	[CashDiscountAmount] MONEY NOT NULL DEFAULT 0,
	[RoundOffAmount] MONEY NOT NULL DEFAULT 0,
	[TotalAmount] MONEY NOT NULL DEFAULT 0,
	[Remarks] VARCHAR(MAX) NULL,
	[DocumentUrl] VARCHAR(MAX) NULL,
	[CreatedBy] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'India Standard Time')),
	[CreatedFromPlatform] VARCHAR(MAX) NOT NULL,
	[Status] BIT NOT NULL DEFAULT 1,
	[LastModifiedBy] INT NULL,
	[LastModifiedAt] DATETIME NULL, 
	[LastModifiedFromPlatform] VARCHAR(MAX) NULL,
    CONSTRAINT [FK_PurchaseReturn_ToCompany] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([Id]),
    CONSTRAINT [FK_PurchaseReturn_ToLedger] FOREIGN KEY ([PartyId]) REFERENCES [Ledger]([Id]), 
    CONSTRAINT [FK_PurchaseReturn_ToFinancialYear] FOREIGN KEY ([FinancialYearId]) REFERENCES [dbo].[FinancialYear]([Id]),
    CONSTRAINT [FK_PurchaseReturn_ToUser] FOREIGN KEY ([CreatedBy]) REFERENCES [User]([Id]),
	CONSTRAINT [FK_PurchaseReturn_LastModifiedBy_ToUser] FOREIGN KEY ([LastModifiedBy]) REFERENCES [User]([Id])
)
