CREATE TABLE [dbo].[PurchaseOrder]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TransactionNo] VARCHAR(100) NOT NULL UNIQUE, 
	[CompanyId] INT NOT NULL,
	[VendorId] INT NOT NULL,
	[GarageId] INT NOT NULL,
    [PurchaseId] INT NULL , 
    [TransactionDateTime] DATETIME NOT NULL,
	[FinancialYearId] INT NOT NULL,
	[TotalItems] INT NOT NULL DEFAULT 0,
	[TotalQuantity] MONEY NOT NULL DEFAULT 0,
    [Remarks] VARCHAR(MAX) NULL,
	[CreatedBy] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT (((getdate() AT TIME ZONE 'UTC') AT TIME ZONE 'India Standard Time')),
	[CreatedFromPlatform] VARCHAR(MAX) NOT NULL,
	[Status] BIT NOT NULL DEFAULT 1,
	[LastModifiedBy] INT NULL,
	[LastModifiedAt] DATETIME NULL, 
	[LastModifiedFromPlatform] VARCHAR(MAX) NULL,
	CONSTRAINT [FK_PurchaseOrder_ToCompany] FOREIGN KEY ([CompanyId]) REFERENCES [Company]([Id]),
    CONSTRAINT [FK_PurchaseOrder_ToLedger] FOREIGN KEY ([VendorId]) REFERENCES [Ledger]([Id]), 
    CONSTRAINT [FK_PurchaseOrder_ToGarage] FOREIGN KEY ([GarageId]) REFERENCES [Garage]([Id]),
    CONSTRAINT [FK_PurchaseOrder_ToPurchase] FOREIGN KEY ([PurchaseId]) REFERENCES [Purchase]([Id]),
	CONSTRAINT [FK_PurchaseOrder_ToFinancialYear] FOREIGN KEY ([FinancialYearId]) REFERENCES [dbo].[FinancialYear]([Id]),
    CONSTRAINT [FK_PurchaseOrder_ToUser] FOREIGN KEY ([CreatedBy]) REFERENCES [User]([Id]),
	CONSTRAINT [FK_PurchaseOrder_LastModifiedBy_ToUser] FOREIGN KEY ([LastModifiedBy]) REFERENCES [User]([Id])
)
