<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;CS8669;CS8632</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;CS8669;CS8632</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.2" />
    <PackageReference Include="Syncfusion.Blazor.Calendars" Version="32.1.24" />
    <PackageReference Include="Syncfusion.Blazor.DropDowns" Version="32.1.24" />
    <PackageReference Include="Syncfusion.Blazor.Grid" Version="32.1.24" />
    <PackageReference Include="Syncfusion.Blazor.Inputs" Version="32.1.24" />
    <PackageReference Include="Syncfusion.Blazor.Notifications" Version="32.1.24" />
    <PackageReference Include="Syncfusion.Blazor.Popups" Version="32.1.24" />
    <PackageReference Include="Syncfusion.Blazor.Spinner" Version="32.1.24" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="32.1.24" />
    <PackageReference Include="Toolbelt.Blazor.HotKeys2" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\VizarLibrary\VizarLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Toolbelt.Blazor.HotKeys2" />
    <Using Include="Vizar.Shared.Services" />
  </ItemGroup>

</Project>