CREATE TABLE [dbo].[Company]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(500) NOT NULL UNIQUE, 
    [Code] VARCHAR(20) NOT NULL UNIQUE, 
    [StateUTId] INT NULL, 
    [GSTNo] VARCHAR(MAX) NULL,
    [PANNo] VARCHAR(MAX) NULL,
    [CINNo] VARCHAR(MAX) NULL,
    [Alias] VARCHAR(MAX) NULL, 
    [Phone] VARCHAR(10) NULL, 
    [Email] VARCHAR(MAX) NULL, 
    [Address] VARCHAR(MAX) NULL, 
    [Remarks] VARCHAR(MAX) NULL, 
    [Status] BIT NOT NULL DEFAULT 1, 
    CONSTRAINT [FK_Company_ToStateUT] FOREIGN KEY ([StateUTId]) REFERENCES [StateUT](Id)
)
