name: Setup Secrets

on:
  workflow_call:

jobs:
  setup-secrets:
    runs-on: windows-latest
    
    steps:
      - name: Create Secrets.local_secrets.cs
        run: |
          $secretsContent = @"
          namespace VizarLibrary.DataAccess;

          public static partial class Secrets
          {
              static Secrets()
              {
                  AzureConnectionString = "${{ secrets.AzureConnectionString }}";

                  AzureBlobStorageConnectionString = "${{ secrets.AzureBlobStorageConnectionString }}";
                  AzureBlobStorageAccountKey = "${{ secrets.AzureBlobStorageAccountKey }}";

                  SyncfusionLicense = "${{ secrets.SyncfusionLicense }}";

                  EmailPassword = "${{ secrets.EmailPassword }}";

                  ToEmail = "${{ secrets.ToEmail }}";
              }
          }
          "@
          Set-Content -Path "VizarLibrary/DataAccess/Secrets.local_secrets.cs" -Value $secretsContent
          echo "✅ Secrets file created successfully"
