name: Deploy for Windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    
    - name: Install .NET MAUI Workload
      run: dotnet workload install maui --skip-sign-check
    
    - name: Create Secrets.local_secrets.cs
      run: |
        $secretsContent = @"
        namespace VizarLibrary.DataAccess;

        public static partial class Secrets
        {
            static Secrets()
            {
                AzureConnectionString = "${{ secrets.AZURE_CONNECTION_STRING }}";
                LocalConnectionString = "${{ secrets.LOCAL_CONNECTION_STRING }}";

                AzureBlobStorageConnectionString = "${{ secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING }}";
                AzureBlobStorageAccountKey = "${{ secrets.AZURE_BLOB_STORAGE_ACCOUNT_KEY }}";

                SyncfusionLicense = "${{ secrets.SYNCFUSION_LICENSE }}";

                EmailPassword = "${{ secrets.EMAIL_PASSWORD }}";

                ToEmail = "${{ secrets.TO_EMAIL }}";
            }
        }
        "@
        Set-Content -Path "VizarLibrary/DataAccess/Secrets.local_secrets.cs" -Value $secretsContent
    
    - name: Restore dependencies
      run: dotnet restore Vizar/Vizar/Vizar.csproj
    
    - name: Publish Windows MAUI App
      run: dotnet publish Vizar/Vizar/Vizar.csproj -f net10.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None -o Vizar/Vizar/publish/windows
    
    - name: Create Zip Archive
      run: Compress-Archive -Path "Vizar/Vizar/publish/windows/*" -DestinationPath "Vizar.zip" -Force
    
    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Vizar-Windows
        path: Vizar.zip
